[project]
name = "intro-python-concurrency"
version = "0.1.0"
description = "Introduction to concurrent programming in Python"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jupyterlab>=4.4.7",
]
